spring:
  config:
    activate:
      on-profile: dev
  datasource:
#    url: jdbc:h2:mem:mutrawdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
    url: jdbc:postgresql://localhost:5438/mutrawdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop # not for production
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2
message: You are using the development profile